### ISSUE TITLE
Q: Is this project dead?

### ISSUE THREAD

**Issue by TLogik** [AppMetrics/GrafanaCloudHostedMetrics#1]
Just wanted to know if the project is dead or what the status is in general.
We are looking into using it but for our production env. we would properly not go for Alpha :-)
Maybe we could contribute if we know the issues at hand.

**Comment by alhardy** [comment]
@TLogik nope it's not dead. I initally picked this up when going to apply it at my workplace but was unable to get budget at the time. I've moved on since and have budget now so your timing is perfect.

Problem was that there is no free version of Grafana Hosted Metrics for me to continue to dev on.

I can't recall the pending issues and unfortunately didn't log them, I'm only now starting to pick this back up.

Contributions would be awesome.

**Comment by alhardy** [comment]
@TLogik  an alpha package is pushed
